apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gox
  janus-idp.io/tekton: gox
  backstage.io/kubernetes-id: gox
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gox
resources:
- deployment.yaml
- route.yaml
- service.yaml
