apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gox-gitops
  description: This is GitOps manifest for gox   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: gox
    janus-idp.io/tekton: gox 
    backstage.io/kubernetes-id: gox 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gox
